### ISSUE TITLE
Feature request: support InfluxDB v2 API

### ISSUE THREAD

**Issue by nielsvn92** [balmli/homey-influxdb#1]
Hi,

Awesome project! I created the same app some time ago, but never placed it in the app store since it stopped working at some point.
In the meanwhile, InfluxDB Cloud introduced a free tier for a hosted InfluxDB instance. I'm trying that now with your app, but I can't connect to my instance. I'm guessing it's because the server uses the InfluxDB v2 API, and your app uses v1?

It would be awesome if you could add support for InfluxDB v2.
See https://github.com/influxdata/influxdb-client-js on how to connect an instance.
You could also just connect directly, without using any client: https://v2.docs.influxdata.com/v2.0/reference/api/
I'm happy to provide credentials to my instance if you want to test it.

Kind regards,
Niels van Nieuwenburg

**Comment by balmli** [comment]
Hi,

Thanks for the feedback!  And links for the newer client.

Yes, will fix :-)

**Comment by balmli** [comment]
v. 0.9.6 with support for InfluxDb v2 and InfluxDb cloud, is not ready for testing:

https://homey.app/a/homey.influxdb/test/

Please test :-)

**Comment by nielsvn92** [comment]
Woa, that was fast. I Just set it up and it seems to work. Awesome job!
Ill keep testing it for a while.
