### ISSUE TITLE
Metrics dont seem to arrive in InfluxDB

### ISSUE THREAD

**Issue by wietse292** [balmli/homey-influxdb#11]
Hi,

I have a question regarding the influxdb exporter for homey.
It appears to be connected to my InfluxDB v2 database and also sending measurements but nothing is showing up in InfluxDB
![image](https://user-images.githubusercontent.com/20375756/206334842-243c9f97-4fbd-442a-9f39-be4dcc91a9ca.png)
![image](https://user-images.githubusercontent.com/20375756/206334908-197ca694-d3a6-4b10-be12-4239d88d75ab.png)

I also tried activating cards and changing the interval, but without success.

Is this a known problem or am I missing something here?

**Comment by josteitv** [comment]
@wietse292 Are you using the organization id (e.g. 0a6de3a0503e8000) and not the organization name in the app settings?

**Comment by balmli** [comment]
Have a look at the instructions in Homey Community:
https://community.homey.app/t/app-pro-influxdb/32405/88
