### ISSUE TITLE
App CPU is missing tag_2 (full name of app)

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [balmli/homey-influxdb#3]
For apps we have tag 0 till 2 for storage and memory.  For CPU only tag_0 and 1 are there.  tag_2 in Grafana shows full name.

tag_0 = memory, cpu or storage
tag_1 = homey.influxdb
tag_2 = InfluxDb

**Comment by balmli** [comment]
Thanks for reporting!   I will have a look at it.

**Comment by balmli** [comment]
Fixed in v. 0.9.11
