### ISSUE TITLE
No Flash storage information if only Homey metrics is selected

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [balmli/homey-influxdb#4]
Using the flowcards we can select the amount of traffic. If i set it to Homey metrics, then Homey storage information is not collected. CPU and Memory is collected, only flash storage is missing.

![selected metrics](https://user-images.githubusercontent.com/28575285/103168040-64b2c680-4830-11eb-93b1-98cf54ac2b7a.png)

![grafana storage](https://user-images.githubusercontent.com/28575285/103168044-68464d80-4830-11eb-85f7-cd85977b99ec.png)

**Comment by balmli** [comment]
Yes, when selecting "Homey metrics", the `system.getStorageInfo()` call is skipped to reduce the load on the Homey.

If you select "Homey and app metrics" storage_total and storage_free will be save to InfluxDb,
