### ISSUE TITLE
Add settings page instead of flow cards

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [balmli/homey-influxdb#5]
The principle using flowcards to set settings is a bit odd, these are settings which are better in place in a settings page of the app itself. I have to run the flow every time the system starts, which of course is no problem to implement, but its not consequent in relation to many other apps in Homey.

**Comment by balmli** [comment]
The settings is stored in "settings", and used every time the app is started.  It should not be necessary to run a flow to set this every time the system starts.
