### ISSUE TITLE
Possible to set/unset which devices (metrics) are exported

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [balmli/homey-influxdb#6]
To make it possible to select which metrics of all available devices should be exported, using a settings page in the app and not using a flowcard.

Currently every metric of every device is automatically exported, but it is not always needed to export metric of all devices and only for a selection of devices

It would be very nice if it is possible using a settings page in the app to tell which devices should be exported and which not. Whereby the default is no export and only by enabling devices in the InfluxDB app settings page, the device metrics are exported and remember the settings during a reboot.

Please look at apps like [Heimdall](https://github.com/daneedk/com.uc.heimdall) and [MQTT Hub](https://github.com/harriedegroot/nl.hdg.mqtt) for examples how to search for devices and select them.

**Comment by balmli** [comment]
Sorry, I'm not going to implement this.
