### ISSUE TITLE
Feature: Logging

### ISSUE THREAD

**Issue by jonkristian** [balmli/homey-influxdb#7]
First of all, thanks for this great app.

I have a feature suggestions which I think would take this to another level. Add ability to pass logs to influxdb. For instance, in flows people could add influx message with whatever they'd like, when the flow runs the message and timestamp is passed to influxdb.

Right now I'm using Simple LOG app, which is nice but pretty limited, being able to search the logs and tie logs to other metrics would be really awesome.

**Comment by balmli** [comment]
Will be supported in v. 1.1.0
