### ISSUE TITLE
Is homey-influxdb still working?

### ISSUE THREAD

**Issue by juliank** [balmli/homey-influxdb#9]
I see it is a few years since the last commit to homey-influxdb. Is the app known to still be working?

I've got version 0.9.14 of the app installed on my Homey Pro (Early 2019 model, Homey software version 8.0.0 (but I had the same issue with the previous 7.4.3 version of Homey)). I also have an InfluxDB cloud instance running, and I have configured the app with all necessary connection details - including organization id and api token.

According to the status page in the app, it is connected. But no measurements have been sent:
<img src="https://user-images.githubusercontent.com/659428/176989339-c30b1c4a-56dd-4269-a46b-ddcbfe138db5.png" width="300" />

I have tried creating a flow with the "Homey and app metrics => enable" card, but triggering this didn't make any difference.

Are there somewhere I can get hold of detailed logs for what might be wrong? (I know about the "Create diagnostics report" in the app's settings, but since those only are sent directly to the app developer, they don't help me much.)

**Comment by Sil0x0000** [comment]
+1

**Comment by PeterKawa** [comment]
I just installed influxdb v.1 on a local Debian server and it works very well
